APP         :=CreateIndex
TARGET      :=CreateIndex
CONFIG      :=
STRIP_FLAG  := N

INCLUDE     += 
LIB         +=
#-----------------------------------------------------------------------
include ../../util/comm/comm.mk
include ../../protocol/protocol.mk
include ../../util/mk/release.mk
include /usr/local/tars/cpp/makefile/makefile.tars

CFLAGS      = -std=c++11 -g -Wno-deprecated -Wall
#-----------------------------------------------------------------------
