APP         :=DelDcache
TARGET      :=DelDcache
CONFIG      :=
STRIP_FLAG  := N

INCLUDE     += 
LIB         +=
#-----------------------------------------------------------------------
include /home/puff/project/dcache/wetaxCenter/center/util/comm/comm.mk
include /home/puff/project/dcache/wetaxCenter/center/util/dataop/dataop.mk
include /home/puff/project/dcache/wetaxCenter/center/protocol/protocol.mk
include /home/puff/project/yunpiao/server/protocol/protocol.mk
include /usr/local/tars/cpp/makefile/makefile.tars
