APP         :=CreateIndex
TARGET      :=CreateIndex
CONFIG      :=
STRIP_FLAG  := N

INCLUDE     += 
LIB         +=
#-----------------------------------------------------------------------
include ../protocol/protocol.mk
include ../util/mk/release.mk
include /usr/local/tars/cpp/makefile/makefile.tars


